export default [
    {
        key:'1',
        title:'首页',
        icon:'home',
        path:'/admin/home'
     },
     {
         key:'2',
         title:'管理员',
         icon:'admin',
         path:'/admin/admins',
         children:[
             {
                key:'2-1',
                title:'管理员列表',
                icon:'admin',
                path:'/admin/adminlist',
             },
             {
                key:'2-2',
                title:'管理员信息',
                icon:'admin',
                path:'/admin/adminadd',
             },
         ]
     },
     {
         key:'3',
         title:'用户管理',
         icon:'user',
         path:'/admin/user',
         children:[
             {
            key:'3-1',
            title:'用户添加',
            path:'/admin/useradd'
         },
         {
             key:'3-2',
             title:'用户列表',
             path:'/admin/userlist'
          }
     ]
         
     },
     {
        key:'4',
        title:'图书管理',
        icon:'home',
        path:'admin/book',
        children:[
            {
           key:'4-1',
           title:'图书添加',
           path:'/admin/bookadd'
        },
        {
            key:'4-2',
            title:'图书列表',
            path:'/admin/booklist'
         }
        ]
     },
     {
        key:'5',
        title:'设置',
        icon:'home',
        path:'/admin/set'
     },

    
        ]